my_mrr_pipeline:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: dev.duckdb
      threads: 4

    prod: 
      type: duckdb
      path: "md:my_mrr_db?motherduck_token={{ env_var('MOTHERDUCK_TOKEN') }}"
      schema: main
      threads: 4 
